export const CERTIFICATION_OPTIONS = [
  'IBM Full Stack Software Developer',
  'Meta Front-End Developer',
  'Meta Back-End Developer',
  'AWS Certified Developer – Associate',
  'Microsoft Azure Developer Associate',
  'MongoDB Certified Developer Associate',
  'Node.js Application Developer',
  'Oracle Java SE Developer',
  'Google Cloud Associate Cloud Engineer',
  'Certified Kubernetes Application Developer (CKAD)',
  'Docker Certified Associate',
  'Git & GitHub Certification',
  'REST API Development Certification',
  'TypeScript Developer Certification',
  'React Developer Certification',
  'Express.js Developer Certification',
  'Full Stack Web Development Certification',
  'Full Stack Software Developer Certification',
  'MERN Stack Developer Certification',
  'Angular Developer Certification',
  'Vue.js Developer Certification',
  'JavaScript Developer Certification',
  'Advanced JavaScript Certification',
  'HTML5 & CSS3 Certification',
  'Node.js Backend Developer Certification',
  'Express.js API Developer Certification',
  'RESTful API Developer Certification',
  'GraphQL Developer Certification',
  'Java Backend Developer Certification',
  'Spring Boot Developer Certification',
  'SQL Developer Certification',
  'PostgreSQL Developer Certification',
  'MySQL Database Developer Certification',
  'Azure Solutions Architect Expert',
  'Google Cloud Digital Leader',
  'Google Professional Cloud Developer',
  'Google Professional Cloud Architect',
  'Docker & Containerization Certification',
  'Kubernetes Administrator Certification (CKA)',
  'Software Testing Certification',
  'ISTQB Certified Tester Foundation Level',
  'Automation Testing Certification',
  'Web Application Security Certification',
  'OWASP Secure Coding Certification',
  'Cybersecurity Fundamentals Certification',
];
